version: '3.8'

services:
# container 1: POSTGRESQL databse
  db:
    image: pgvector/pgvector:pg15
    env_file:
      - .env 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Container 2: FastAPI application
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    image: redis:7
    ports:
    - "6379:6379"

  celery_worker:
    build: .
    env_file:
    - .env
    command: celery -A app.services.worker.celery_app worker --loglevel=info
    depends_on:
      - db
      - redis 



volumes:
  postgres_data:

